### ISSUE TITLE
Npm install is inconsistent with the current version

### ISSUE THREAD

**Issue by andy0727** [ragingwind/gulp-crisper#14]
In Commit 6406cae, I think you changed the opts. But if I use npm install to install the package, it will get the Commit 22a3910 Because the version is always 1.0.0. Which means the JsFileName will always be overwritten because it doesn't have that opts reverted.

**Comment by ragingwind** [comment]
done by https://github.com/ragingwind/gulp-crisper/commit/edd54105fb4717585307a2264110cfa6e19edb82
