### ISSUE TITLE
Crisper 2.0 released, need an update!

### ISSUE THREAD

**Issue by ebidel** [ragingwind/gulp-crisper#8]
- `scriptInHead: true` is now the default
- There's also a `--always-write-script` flag now

**Comment by ebidel** [comment]
This will probably need to go to 1.0.

**Comment by ragingwind** [comment]
@ebidel sure. thanks for notice

**Comment by ragingwind** [comment]
closed with https://github.com/ragingwind/gulp-crisper/commit/312995352ac4e3f4e2b42db650f24cbcf32b9c38

**Comment by ebidel** [comment]
Sweet!
